- name: Create directory for personal web
  ansible.builtin.file:
    path: /opt/personalweb/{{ container_visualization_name }}/
    state: directory
    mode: '0755'

- name: Render compose template
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: /opt/personalweb/{{ container_visualization_name }}/docker-compose.yaml

- name: Compose deploy
  shell:
    cmd: "docker compose down ; docker compose up -d"
    chdir: "/opt/personalweb/{{ container_visualization_name }}"

